* bm parameters used for adjusting budget share weightings
 BudShare(C,H,T)  budget share of marketed commodity c by household h

 BudShare0(C,H,T)  budget share of marketed commodity c by household h used as template


 DistanceMatrix(H,HP,T) distance to all

 TmpMin(H,T) minimum of row
 TmpLowerNeighbour(H,HP,T) lower neighbour
 TmpUpperNeighbour(H,HP,T) upper neighbour

 TotalDistance(H,T) sum of distances
 DistLower(H,T) distance to lower
 DistUpper(H,T) distance to upper
 WeightLower(H,T) weighting of lower
 WeightUpper(H,T) weighting of upper
